### ISSUE TITLE
Issue with Importing Wordpress Data

### ISSUE THREAD

**Issue by mattdwardle** [datocms/js-datocms-client#69] opened 2020-04-14 20:27 UTC
I am getting some error with the wordpress api importing tool. See console error below:

```(node:19548) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Error: No header link found with rel="https://api.w.org/"
    at locateAPIRootHeader (/usr/local/lib/node_modules/datocms-client/node_modules/wpapi/lib/autodiscovery.js:32:8)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:19548) UnhandledPromiseRejectionWarning: Error: Autodiscovery failed
    at /usr/local/lib/node_modules/datocms-client/node_modules/wpapi/wpapi.js:465:10
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:19548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by matjack1** [comment] 2020-04-15 09:18
hello @mattdwardle can you please confirm that your WP instance has the `/wp-json` endpoint active and reachable from where you run the script?

If so, can you please help me reproduce your error? Maybe send over at https://www.datocms.com/support/ more details on your WP instance and I can try to import myself?

**Comment by mattdwardle** [comment] 2020-04-15 12:00
Hi @matjack1 we have JWT authentication on our wordpress api. Does the app get a bearer token first before making the request or is there some way I can pass it as props?

**Comment by matjack1** [comment] 2020-04-15 12:40
we are using this library: https://github.com/WP-API/node-wpapi#authentication which looks like it's only allowing user/pass auth at the moment?

You can try more by yourself by tweaking this: https://github.com/datocms/js-datocms-client/blob/master/src/wpImport/command.js maybe?

Let me know if I can help you further!

**Comment by matjack1** [comment] 2020-04-27 15:55
I'm closing this for now, but if you need anything else from me feel free to reopen!

**Closed by matjack1** 2020-04-27 15:55 UTC
Labels: triage

**Comment by monsieurnebo** [comment] 2020-08-19 20:42
For people having trouble importing WP (e.g. authentication, wordpress.com hosted, ...), you should be able to:

1. Login your WP as admin
2. Export the WP content
3. Create a local instance (the easy way is through Local by Flywheel)
4. Import the data in the local WP
5. Use `dato-client` on the local instance
6. ???
7. PROFIT
