### ISSUE TITLE
Issues on middleman build

### ISSUE THREAD

**Issue by meandkareem** [datocms/js-datocms-client#50] opened 2019-10-09 13:17 UTC
When I try to 

After including node module with 

var SiteClient = require('datocms-client').SiteClient;
const client = new SiteClient("<My API KEY> ");

i get this error on midleman build ... local and netlify 

events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: Line 1720: Unexpected token function
    at constructError (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:2505:15)
    at consumeSemicolon (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:2620:13)
    at parseStatement (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:4816:9)
    at parseStatementListItem (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:3989:16)
    at parseFunctionSourceElements (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:4869:23)
    at parseFunctionExpression (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:5074:16)
    at parsePrimaryExpression (/Users/milemodic/Sites/uec/node_modules/esprima/esprima.js:3273:24)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/Users/milemodic/Sites/uec/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:198:13)
    at DestroyableTransform._transform (/Users/milemodic/Sites/uec/node_modules/gulp-strip-debug/index.js:22:9)
    at DestroyableTransform.Transform._read (/Users/milemodic/Sites/uec/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/milemodic/Sites/uec/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/milemodic/Sites/uec/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/milemodic/Sites/uec/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/milemodic/Sites/uec/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/Users/milemodic/Sites/uec/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)

**Comment by matjack1** [comment] 2019-10-09 13:28
Hello @meandkareem are you only adding those two lines and you get that error?

I cannot find any sign of our module in the stack trace, do you agree? Can you give me a bit more context on the file you are running so that I can try replicating the error myself?

**Comment by meandkareem** [comment] 2019-10-09 13:32
Yes. 

Soon as I add these two lines I get errors above. 

Everything works fine when I'm working with middleman server .. but soon as I or netlify runs build production command it fails. When I comment these two lines everything works fine.

**Comment by matjack1** [comment] 2019-10-14 11:06
sorry @meandkareem I cannot reproduce your error. Can you please give me access to your repo so that I can see what's going on?

**Comment by matjack1** [comment] 2020-01-14 14:52
Closing for lack of reply

**Closed by matjack1** 2020-01-14 14:52 UTC
Labels: triage
