### ISSUE TITLE
Breaking change between 0.6.1 and 0.6.2, 'path' of undefined

### ISSUE THREAD

**Issue by Siilwyn** [datocms/js-datocms-client#21] opened 2018-08-08 15:14 UTC
Over at [hike-one](https://github.com/voorhoede/hike-one) we're using the Dato client to dump data, after upgrading from version `0.6.1` to `0.6.2` running `dato dump` returns:
```
❌ Error dumping data TypeError: Cannot read property 'path' of undefined
    at File.get (/home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/local/fields/File.js:60:26)
    at File.url (/home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/local/fields/File.js:42:52)
    at image (/home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/utils/seoTagsBuilder.js:137:23)
    at /home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/utils/seoTagsBuilder.js:148:18
    at Array.reduce (<anonymous>)
    at seoTagsBuilder (/home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/utils/seoTagsBuilder.js:147:34)
    at Item.get (/home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/local/Item.js:230:44)
    at Item.toMap (/home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/local/Item.js:105:16)
    at /home/siilwyn/codeground/hike-one/node_modules/datocms-client/lib/local/fields/Links.js:34:17
    at Array.map (<anonymous>)
```

[Comparing these two versions](https://github.com/datocms/js-datocms-client/compare/v0.6.1...v0.6.2) not a lot has changed but I guess this new filter causes something to be `undefined`? Thoughts?

Sidenote: the latest version `0.6.3` has the issue too.

**Comment by matjack1** [comment] 2019-05-14 15:29
@Siilwyn I think this problem is linked to your specific project.

I think it's because you have an empty "Global SEO settings" in your project's settings.

Anyway, while digging into this I've found a related error in the current version, that is now fixed here: https://github.com/datocms/js-datocms-client/pull/37

I'm going to close this for now, but if you feel like you need more info just reopen it with more details, or contact me over support@datocms.com if the problem is linked to a specific project.

**Closed by matjack1** 2019-05-14 15:29 UTC

**Comment by Siilwyn** [comment] 2019-05-17 12:01
Thank you @matjack1!
